// <auto-generated />
using System;
using FunktsioonideUurimine.Api.Andmed;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FunktsioonideUurimine.Api.Andmed.Migratsioonid
{
    [DbContext(typeof(FunktsiooniKontekst))]
    partial class FunktsiooniKontekstModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("FunktsioonideUurimine.Api.Mudelid.FunktsiooniUurimine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ekstreemumid")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kaanupunktid")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("KriitilisedPunktid")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kumerus")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LuodudAeg")
                        .HasColumnType("TEXT");

                    b.Property<string>("Maaramispiirkond")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Monotoonsus")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("MuudetudAeg")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nullkohad")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Positiivsus")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("TeineTuletis")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tuletis")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<double>("VahemikAlgus")
                        .HasColumnType("REAL");

                    b.Property<double>("VahemikLopp")
                        .HasColumnType("REAL");

                    b.Property<string>("Valem")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LuodudAeg");

                    b.ToTable("FunktsiooniUurimised", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
